services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - upload_temp:/app/upload_temp
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,nginx
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FILE_UPLOAD_MAX_MEMORY_SIZE=5242880
      - FILE_UPLOAD_TEMP_DIR=/app/upload_temp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A stock_management worker -l info
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - upload_temp:/app/upload_temp
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,nginx
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    expose:
      - "80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    environment:
      - NGINX_MAX_UPLOAD=100M
      - NGINX_CLIENT_MAX_BODY_SIZE=100M

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  upload_temp:
