version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=/api
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - upload_temp:/app/upload_temp
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN:-localhost,127.0.0.1,backend,frontend,nginx}
      - DB_NAME=${DB_NAME:-stock_db}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FILE_UPLOAD_MAX_MEMORY_SIZE=5242880
      - FILE_UPLOAD_TEMP_DIR=/app/upload_temp
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: celery
    command: -A stock_management worker -l info
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - upload_temp:/app/upload_temp
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME:-stock_db}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME:-stock_db}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-stock_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - upload_temp:/var/www/upload_temp
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  upload_temp:
