name: CI/CD Pipeline

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up environment
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Make scripts executable
        run: |
          chmod +x scripts/postInstall.sh
          chmod +x scripts/postDeploy.sh

      - name: Deploy to Elestio
        env:
          ELESTIO_TOKEN: ${{ secrets.ELESTIO_TOKEN }}
          ELESTIO_CNAME: "catalogmanagementsystem-u23037.vm.elestio.app"
        run: |
          # Run post-install script
          ./scripts/postInstall.sh
          
          # Run post-deploy script
          ./scripts/postDeploy.sh

      - name: Verify Deployment
        run: |
          # Wait for deployment to stabilize
          sleep 30
          
          # Check if the application is accessible
          curl -f https://catalogmanagementsystem-u23037.vm.elestio.app/health || exit 1
